/*
 *
 * Main constants
 *
 */

export const CHANGE_IMAGES = 'app/Main/CHANGE_IMAGES';

export const CLASSIFY_IMAGES = 'app/Main/CLASSIFY_IMAGES';
export const CLASSIFY_IMAGES_SUCCESS = 'app/Main/CLASSIFY_IMAGES_SUCCESS';
export const CLASSIFY_IMAGES_ERROR = 'app/Main/CLASSIFY_IMAGES_ERROR';

export const LOAD_UPLOADED_IMAGES = 'app/Main/LOAD_UPLOADED_IMAGES';
export const LOAD_UPLOADED_IMAGES_SUCCESS =
  'app/Main/LOAD_UPLOADED_IMAGES_SUCCESS';

export const CLEAR_UPLOADED_IMAGES = 'app/Main/CLEAR_UPLOADED_IMAGES';
export const CLEAR_UPLOADED_IMAGES_SUCCESS =
  'app/Main/CLEAR_UPLOADED_IMAGES_SUCCESS';
